-- Guardado de partida de Mi primer juego 2D 

DROP DATABASE IF EXISTS guardado; 
CREATE DATABASE IF NOT EXISTS guardado; 
USE guardado; 

CREATE TABLE  IF NOT EXISTS jugador(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    Pos_X INT NOT NULL,
    POS_Y INT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventario(
	ID INT NOT NULL PRIMARY KEY, 
    OBJ_Nombre VARCHAR(45) NOT NULL,
    Pos_X INT NOT NULL, 
    Pos_Y INT NOT NULL 

); 


